version: '3.1'

services:

 opscloud-server:
  image:  tomcat:8.0.36-jre8
  volumes:
   - ./data/usr/local/tomcat/webapps:/usr/local/tomcat/webapps:rw
   - ./data/data/www/data:/data/www/data:rw
  restart: always
  environment:
    TZ: Asia/Shanghai
  ports:
   - "8080:8080"
  user: root
  stop_grace_period: 30s