version: '3.1'

services:

 apacheds-server:
  image: dockergogolj/apacheds:2-centos7
  command: ["/opt/apacheds-2.0.0.AM25/bin/apacheds", "console", "default"]
  restart: always
  environment:
    TZ: Asia/Shanghai
  ports:
   - "10389:10389"
  user: root
  healthcheck:
    test: ["CMD", "/opt/apacheds-2.0.0.AM25/bin/apacheds", "status", "default"]
    interval: 10s
    timeout: 5s
    retries: 3
  stop_grace_period: 10s