apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini: |
    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db
    [security]
    admin_user = test
    admin_password = test 
