apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "vol-mysql"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    limits:
      storage: 5Gi
    requests:
      storage: 1Gi
#prome
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "vol-prometheus"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus 
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    limits:
      storage: 10Gi
    requests:
      storage: 1Gi
#gitlab
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "vol-prometheus"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus 
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    limits:
      storage: 10Gi
    requests:
      storage: 1Gi
