version: '3.1'

services:

 confluence-server:
  image: atlassian/confluence-server:7.1-ubuntu
  volumes:
   - ./data/var/atlassian/application-data/confluence:/var/atlassian/application-data/confluence:rw
  environment:
    TZ: Asia/Shanghai
  ports:
   - "8090:8090"
  user: root
  stop_grace_period: 1m